# API Forwarding Solution with EventBus

---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo
spec:
  nats:
    native:
      replicas: 1

---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: local-api-eventsource
  namespace: argo
spec:
  eventBusName: default
  resource:
    workflow-watch:
      namespace: argo
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      eventTypes:
        - ADD
---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: local-forwarding-sensor
  namespace: argo
spec:
  eventBusName: default
  dependencies:
    - name: workflow-created
      eventSourceName: local-api-eventsource
      eventName: workflow-watch
  triggers:
    - template:
        name: forward-workflow-submission
        http:
          url: "http://192.168.88.128:13337/"
          method: "POST"
          payload:
            - src:
                dependencyName: "workflow-created"
              dest: "workflow_submission"

