# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WorkflowEvent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, primary_endpoint: str=None, secondary_endpoint: str=None, files: List[str]=None):  # noqa: E501
        """WorkflowEvent - a model defined in Swagger

        :param primary_endpoint: The primary_endpoint of this WorkflowEvent.  # noqa: E501
        :type primary_endpoint: str
        :param secondary_endpoint: The secondary_endpoint of this WorkflowEvent.  # noqa: E501
        :type secondary_endpoint: str
        :param files: The files of this WorkflowEvent.  # noqa: E501
        :type files: List[str]
        """
        self.swagger_types = {
            'primary_endpoint': str,
            'secondary_endpoint': str,
            'files': List[str]
        }

        self.attribute_map = {
            'primary_endpoint': 'primary_endpoint',
            'secondary_endpoint': 'secondary_endpoint',
            'files': 'files'
        }
        self._primary_endpoint = primary_endpoint
        self._secondary_endpoint = secondary_endpoint
        self._files = files

    @classmethod
    def from_dict(cls, dikt) -> 'WorkflowEvent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WorkflowEvent of this WorkflowEvent.  # noqa: E501
        :rtype: WorkflowEvent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def primary_endpoint(self) -> str:
        """Gets the primary_endpoint of this WorkflowEvent.


        :return: The primary_endpoint of this WorkflowEvent.
        :rtype: str
        """
        return self._primary_endpoint

    @primary_endpoint.setter
    def primary_endpoint(self, primary_endpoint: str):
        """Sets the primary_endpoint of this WorkflowEvent.


        :param primary_endpoint: The primary_endpoint of this WorkflowEvent.
        :type primary_endpoint: str
        """

        self._primary_endpoint = primary_endpoint

    @property
    def secondary_endpoint(self) -> str:
        """Gets the secondary_endpoint of this WorkflowEvent.


        :return: The secondary_endpoint of this WorkflowEvent.
        :rtype: str
        """
        return self._secondary_endpoint

    @secondary_endpoint.setter
    def secondary_endpoint(self, secondary_endpoint: str):
        """Sets the secondary_endpoint of this WorkflowEvent.


        :param secondary_endpoint: The secondary_endpoint of this WorkflowEvent.
        :type secondary_endpoint: str
        """

        self._secondary_endpoint = secondary_endpoint

    @property
    def files(self) -> List[str]:
        """Gets the files of this WorkflowEvent.


        :return: The files of this WorkflowEvent.
        :rtype: List[str]
        """
        return self._files

    @files.setter
    def files(self, files: List[str]):
        """Sets the files of this WorkflowEvent.


        :param files: The files of this WorkflowEvent.
        :type files: List[str]
        """

        self._files = files
